-- AlterTable
ALTER TABLE "product" ALTER COLUMN "g" SET DEFAULT 0,
ALTER COLUMN "gg" SET DEFAULT 0,
ALTER COLUMN "m" SET DEFAULT 0,
ALTER COLUMN "p" SET DEFAULT 0,
ALTER COLUMN "pp" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "product_has_order" ALTER COLUMN "g" SET DEFAULT 0,
ALTER COLUMN "gg" SET DEFAULT 0,
ALTER COLUMN "m" SET DEFAULT 0,
ALTER COLUMN "p" SET DEFAULT 0,
ALTER COLUMN "pp" SET DEFAULT 0,
ALTER COLUMN "order_product_value" DROP DEFAULT;
